apiVersion: automation.cloudbees.io/v1alpha1
kind: action

name: "CloudBees Platform - Example Action"
description: "Prints a message"
env:
  REVISION: 8

runs:
  using: "composite"
  steps:
    - name: Printing in revision {{REVISION}} 
      uses: docker://ubuntu:latest
      run: |
        echo Revision {{REVISION}}
